apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - secret.yaml
  - postgres.yaml
  - keycloak.yaml
  - http-redirect.yaml
configMapGenerator:
  - name: keycloak-realm
    files:
      - realm-osb-api.json
generatorOptions:
  disableNameSuffixHash: true
