apiVersion: v2
name: osb
description: Open Service Broker API + Admin BFF/UI for Kubernetes (dogfood)
type: application
version: 0.1.1
appVersion: 0.1.1
kubeVersion: '>=1.25.0-0'
home: https://github.com/eumicro/osb-api
sources:
  - https://github.com/eumicro/osb-api
keywords:
  - osb
  - service-broker
  - quarkus
maintainers:
  - name: eumicro
    url: https://github.com/eumicro
