{{- $needSecret := or .Values.config.postgres.password .Values.config.n8n.clientToken .Values.config.n8n.bridgeSecret -}}
{{- if $needSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osb.fullname" . }}-credentials
  labels:
    {{- include "osb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.postgres.password }}
  OSB_POSTGRES_PASSWORD: {{ .Values.config.postgres.password | quote }}
  {{- end }}
  {{- if .Values.config.n8n.clientToken }}
  OSB_N8N_CLIENT_TOKEN: {{ .Values.config.n8n.clientToken | quote }}
  {{- end }}
  {{- if .Values.config.n8n.bridgeSecret }}
  OSB_BFF_N8N_BRIDGE_SECRET: {{ .Values.config.n8n.bridgeSecret | quote }}
  {{- end }}
{{- end }}
